baseURL = ""
languageCode = "en-us"
title = "Security notes & write-ups"
theme = "hugo-theme-hello-friend-ng"

PygmentsCodeFences = false
PygmentsStyle = "monokai"

enableGitInfo   = false
enableEmoji     = true
paginate = 10

[author]
  name = "lafx0"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]

  homeSubtitle = "A simple blog to use as a personal reference"

  disableReadOtherPosts = false
  enableSharingButtons = false

  enableThemeToggle = true

  rtl = false

  math = true
  custom_css = ["css/custom.css"]

[params.logo]
  logoMark     = ">"
  logoText     = "lafx0"
  logoHomeLink = "/"
  # Set to a valid CSS color to change the cursor in the logo.
  logoCursorColor    = "#ff531a"
  # Set to a valid CSS time value to change the animation duration, "0s" to disable.
  logoCursorAnimate  = "2s"

#Main Menu
[menu]
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  weight = 1
  url  = "/posts/"

[[menu.main]]
  identifier = "about"
  name = "About"
  weight = 2
  url = "/about/info/"


# Social links
[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/lafx02/"

[[params.social]]
  name = "github"
  url  = "https://github.com/lafx0"
